# Generated by Django 5.0.1 on 2025-04-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsumm',
            name='price',
        ),
        migrations.RemoveField(
            model_name='textsumm',
            name='quantity',
        ),
        migrations.AddField(
            model_name='textsumm',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
