# Generated by Django 5.0.1 on 2025-04-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0002_remove_textsumm_price_remove_textsumm_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsumm',
            name='video',
            field=models.URLField(blank=True, default=''),
        ),
    ]
