# Generated by Django 5.0.1 on 2025-04-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0003_textsumm_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsumm',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
