# Generated by Django 5.0.1 on 2025-04-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0004_textsumm_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textsumm',
            old_name='summary',
            new_name='battle',
        ),
        migrations.AddField(
            model_name='textsumm',
            name='conversion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='textsumm',
            name='death',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='textsumm',
            name='hijrah',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='textsumm',
            name='lineage',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='textsumm',
            name='persecution',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='textsumm',
            name='trait',
            field=models.TextField(default=''),
        ),
    ]
