# Generated by Django 5.0.1 on 2025-05-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0005_rename_summary_textsumm_battle_textsumm_conversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsumm',
            name='image',
            field=models.ImageField(upload_to='FYP Cover Images/'),
        ),
    ]
