# Generated by Django 5.0.1 on 2025-05-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0006_alter_textsumm_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsumm',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='FYP Audio/'),
        ),
    ]
