# Generated by Django 5.0.1 on 2025-05-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0007_textsumm_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsumm',
            name='audio',
        ),
    ]
