# Generated by Django 5.0.1 on 2025-06-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textsumm', '0009_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at'], 'verbose_name': 'Note/Reflection', 'verbose_name_plural': 'Notes & Reflections'},
        ),
    ]
